name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test
      id: test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test
        setup-command: make
        command: "./test mama 19 2.7 mumu 18 3.0 moo 20 2.9"
        input: ''
        expected-output: |-
          Youngest student
          Name: mumu
          Age: 18
          GPA: 3
        comparison-method: contains
        timeout: 10
        max-score: 10
    - name: Test2
      id: test2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test2
        setup-command: make
        command: "./test mama 19 2.7 moo 20 2.9"
        input: ''
        expected-output: |-
          Youngest student
          Name: mama
          Age: 19
          GPA: 2.7
        comparison-method: contains
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_RESULTS: "${{steps.test.outputs.result}}"
        TEST2_RESULTS: "${{steps.test2.outputs.result}}"
      with:
        runners: test,test2
